services:
   vprodb:
      build:
         context: ./Docker-files/db
      images: sahil9079/vpro_db
      container_name: vprodb
      ports:
        - "3306:3306"
      volumes:
        - vprodbdata:/var/lib/mysql
      enviroment:
        - MYSQL_ROOT_PASSWORD=vprodbpass
   vprocache01:
      images: memcached
      ports:
        - "11211:11211"
   vpromq01:
      images: rabbitmq
      ports:
        - "5672:5672"
      enviroment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
   vproapp:
      build: 
         context: ./Docker-files/app
      images: sahil9079/vpro_app
      container_name: vproapp
      ports:
        - "8080:8080"
      volumes:
        - vproappdata:/usr/local/tomcat/webapps 
   vproweb:
      build: 
         context: ./Docker-files/web
      images: sahil9079/vpro_web
      container_name: vproweb
      ports:
        - "80:80"
volumes:
   vprodbdata: {}
   vproappdata: {}

